vim.g.startify_custom_header = {
  "                                       ",
  "                                       ",
  "                                       ",
  "                                       ",
  "                                       ",
  "        Find Files ------------> SPC f f",
  "        Git Files -------------> SPC g f",
  "        Recent Files ----------> SPC f o",
  "        File Tree -------------> Ctrl+ n",
  "                                       ",
  "                                       ",
  "                                       ",
  "                                       ",
  "                                       ",
}
